---
title: On direct systems of implications with graded attributes
author:
  - name: Manuel Ojeda-Hernández
    orcid: 0000-0003-4785-6802
    corresponding: false
    email: manueloh@cs.umu.se
    roles:
      - Investigation
      - Writing
    affiliations:
      - Department of Computing Science, Umeå University, Sweden
  - name: Domingo López-Rodríguez
    orcid: 0000-0002-0172-1585
    corresponding: true
    email: dominlopez@uma.es
    roles:
      - Investigation
      - Writing
    affiliations:
      - Depto. de Matemática Aplicada, Universidad de Málaga, Spain
keywords:
  - Fuzzy attributes
  - Implicational systems
  - Directness
abstract: |
  In this paper the problem of defining direct systems of implications in the fuzzy setting is studied. The directness of systems allows a quick computation of the closure operator in cases such as Fuzzy Formal Concept Analysis. Characterizing these properties in algebraic terms is deeply linked to Simplification Logic. After the theoretical results, some thoughts on algorithms to provide direct systems are also considered.
key-points:
  - A characterization of direct systems of attributes in the fuzzy setting is presented.
  - This characterization leads to a computational method to construct a direct system of implications given a general implicational system with graded attributes.
date: last-modified
bibliography: references.bib
number-sections: false
---

<!-- %\newcommand{\el}[2]{^{\scriptsize #2\!\!}/{#1}} -->
\newcommand{\el}[2]{#1_{#2}}

# Introduction

This document serves as supplementary material for the paper _On direct systems of implications with graded attributes_ submitted to EUSFLAT 2025.

# Detailed example

Let us consider a fuzzy formal context $\mathbb K = (G, M, I)$, where the set of attributes is $M=\{a,b,c,d,e\}$, and such that the valuation lattice, i.e., the lattice $L$ such that $I\in L^{G\times M}$, is $L=\{0, 0.5, 1\}$, equipped with the Lukasiewicz logical structure. If the degree of element $x\in M$ in a set is $y\in L$, we will denote the element as $x_{y}$. 

Take the system of implications:

$$\Sigma = \{\el{a}{0.5}\,\el{b}{0.5}\,d \to a\,b\,c\,e, \quad \el{a}{0.5}\,d\,e \to a\,b\,\el{c}{0.5}\}$$

We will use the `DirectSystem` algorithm to construct a direct system $\Sigma_d$ equivalent to $\Sigma$.

## Iterations

### Iteration 1

We will describe this iteration in detail, the following ones will be more concise.

**Derived implications**

The algorithm loops over all pairs of implications, computing the _derived implication_ when needed (required by the fuzzy exchange condition). In this first iteration, only the two implications are checked, for all $\alpha,\beta\in L$ such that the requirements are met:

Taking 
\begin{align*}
A\to B \quad& = \quad\el{a}{0.5}\,d\,e \to a\,b\,\el{c}{0.5} \\
C\to D \quad& = \quad\el{a}{0.5}\,\el{b}{0.5}\,d \to a\,b\,c\,e,
\end{align*}
the execution of `AddDerived` produces:

- for $\alpha = 0.5$, $\beta = 0.5$, the implication $\el{d}{0.5}\,\el{e}{0.5} \to \el{a}{0.5}\,\el{b}{0.5}\,\el{c}{0.5}$.
- for $\alpha = 1$, $\beta = 0.5$, the implication $\el{a}{0.5}\,d\,e \to \el{b}{0.5}\,\el{c}{0.5}$.
- for $\alpha = 1$, $\beta = 1$, the implication $\el{a}{0.5}\,d\,e \to a\,b\,c$.

Reversing the order in which the implications are considered, i.e., 
\begin{align*}
A\to B \quad& =  \quad\el{a}{0.5}\,\el{b}{0.5}\,d \to a\,b\,c\,e \\
C\to D \quad& = \quad\el{a}{0.5}\,d\,e \to a\,b\,\el{c}{0.5},
\end{align*}
`AddDerived` provides:

- for $\alpha = 0.5$, $\beta = 0.5$, the implication $\el{d}{0.5} \to \el{a}{0.5}\,\el{b}{0.5}$.
- for $\alpha = 0.5$, $\beta = 1$, the implication $d\,e \to a\,b\,\el{c}{0.5}$
- for $\alpha = 1$, $\beta = 1$, the implication $\el{a}{0.5}\,\el{b}{0.5}\,d \to a\,b\,\el{c}{0.5}$

This produces
\begin{align*}
\mathcal D &= \big\{\el{d}{0.5}\,\el{e}{0.5} \to \el{a}{0.5}\,\el{b}{0.5}\,\el{c}{0.5},\quad \el{a}{0.5}\,d\,e \to a\,b\,c,\quad \el{d}{0.5} \to \el{a}{0.5}\,\el{b}{0.5},\\
& \quad d\,e \to a\,b\,\el{c}{0.5},\quad \el{a}{0.5}\,\el{b}{0.5}\,d \to a\,b\,\el{c}{0.5}\big\}
\end{align*}

**Combination phase**

The result of applying `Combine` to $\Sigma$ and $\mathcal D$ follows these steps:

- Add the implication $\el{d}{0.5}\,\el{e}{0.5} \to \el{a}{0.5}\,\el{b}{0.5}\,\el{c}{0.5}$ to $\Sigma$, since there is no implication in $\Sigma$ with the same left-hand side.
- Analogously, add the implications $\el{d}{0.5} \to \el{a}{0.5}\,\el{b}{0.5}$ and $d\,e \to a\,b\,\el{c}{0.5}$ to $\Sigma$.
- Update $\el{a}{0.5}\,d\,e \to a\,b\,\el{c}{0.5} \in \Sigma$ with $\el{a}{0.5}\,d\,e \to a\,b\,c\in\mathcal D$, to obtain the implication $\el{a}{0.5}\,d\,e \to a\,b\,c$.

The value of the variable `change` returned by `Combine` is `true` since there have been modifications to $\Sigma$.

**Result of the iteration**

$\Sigma$ after this iteration:
\begin{align*}
\Sigma & = \big\{\el{a}{0.5}\,\el{b}{0.5}\,d \to a\,b\,c\,e,\quad \el{a}{0.5}\,d\,e \to a\,b\,c,\quad \el{d}{0.5}\,\el{e}{0.5} \to \el{a}{0.5}\,\el{b}{0.5}\,\el{c}{0.5},\\
& \quad\el{d}{0.5} \to \el{a}{0.5}\,\el{b}{0.5},\quad d\,e \to a\,b\,\el{c}{0.5}\big\}
\end{align*}

### Iteration 2

Now, we will summarise the steps, for the sake of readability.

**Derived implications**

\begin{align*}
\mathcal D = & \big\{\el{d}{0.5}\,\el{e}{0.5} \to \el{a}{0.5}\,\el{b}{0.5}\,\el{c}{0.5},\quad d\,\el{e}{0.5} \to a\,b\,c\,e,\quad \el{a}{0.5}\,d\,e \to a\,b\,c, \\
& \quad b\,\el{c}{0.5} \to a\,c\,d,\quad \el{d}{0.5} \to \el{a}{0.5}\,\el{b}{0.5}\,\el{c}{0.5}\,\el{e}{0.5},\quad d\,e \to a\,b\,c, \quad \el{a}{0.5}\,\el{b}{0.5}\,d \to a\,b\,c\big\}
\end{align*}

**Combination phase**

- Update $\el{d}{0.5} \to \el{a}{0.5}\,\el{b}{0.5}$ with $\el{d}{0.5} \to \el{a}{0.5}\,\el{b}{0.5}\,\el{c}{0.5}\,\el{e}{0.5}$ to obtain $\el{d}{0.5} \to \el{a}{0.5}\,\el{b}{0.5}\,\el{c}{0.5}\,\el{e}{0.5}$.
- Update $d\,e \to a\,b\,\el{c}{0.5}$ with $d\,e \to a\,b\,c$ to obtain $d\,e \to a\,b\,c$.
- Add $d\,\el{e}{0.5} \to a\,b\,c\,e$ to $\Sigma$.

Therefore, the variable `change` is again `true` and a new iteration is needed.

**Result of the iteration**

$\Sigma$ after this iteration:
\begin{align*}
\Sigma = & \big\{\el{a}{0.5}\,\el{b}{0.5}\,d \to a\,b\,c\,e,\quad 
\el{a}{0.5}\,d\,e \to a\,b\,c,\quad 
\el{d}{0.5}\,\el{e}{0.5} \to \el{a}{0.5}\,\el{b}{0.5}\,\el{c}{0.5},\\
& \quad \el{d}{0.5} \to \el{a}{0.5}\,\el{b}{0.5}\,\el{c}{0.5}\,\el{e}{0.5},\quad d\,e \to a\,b\,c,\quad d\,\el{e}{0.5} \to a\,b\,c\,e\big\}.
\end{align*}

### Iteration 3

**Derived implications**

\begin{align*}
\mathcal D = & \big\{
\el{d}{0.5} \to \el{a}{0.5}\,\el{b}{0.5}\,\el{c}{0.5}\,\el{e}{0.5},\quad  
d \to a\,b\,c\,e,\quad 
\el{d}{0.5}\,\el{e}{0.5} \to \el{a}{0.5}\,\el{b}{0.5}\,\el{c}{0.5},\quad 
d\,\el{e}{0.5} \to a\,b\,c\,e, \\
& \quad d\,e \to a\,b\,c,\quad 
\el{a}{0.5}\,\el{b}{0.5}\,d \to a\,b\,c\,\el{e}{0.5},\quad 
\el{a}{0.5}\,d\,e \to a\,b\,c\big\}
\end{align*}

**Combination phase**

- Add $d \to a\,b\,c\,e$ to $\Sigma$.

For this reason, `change` is set to `true`.

**Result of the iteration**

The implication system obtained so far is

\begin{align*}
\Sigma = & \big\{
\el{a}{0.5}\,\el{b}{0.5}\,d \to a\,b\,c\,e,\quad 
\el{a}{0.5}\,d\,e \to a\,b\,c,\quad 
\el{d}{0.5}\,\el{e}{0.5} \to \el{a}{0.5}\,\el{b}{0.5}\,\el{c}{0.5},\quad 
\el{d}{0.5} \to \el{a}{0.5}\,\el{b}{0.5}\,\el{c}{0.5}\,\el{e}{0.5},\\
&\quad 
d\,e \to a\,b\,c,\quad 
d\,\el{e}{0.5} \to a\,b\,c\,e,\quad 
d \to a\,b\,c\,e\big\}
\end{align*}

### Iteration 4

**Derived implications**

\begin{align*}
\mathcal D = & \big\{
\el{d}{0.5} \to \el{a}{0.5}\,\el{b}{0.5}\,\el{c}{0.5}\,\el{e}{0.5},\quad 
\el{a}{0.5}\,\el{b}{0.5}\,d \to a\,b\,c\,\el{e}{0.5},\quad 
d\,e \to a\,b\,c,\\
&\quad 
\el{d}{0.5}\,\el{e}{0.5} \to \el{a}{0.5}\,\el{b}{0.5}\,\el{c}{0.5},\quad 
d\,\el{e}{0.5} \to a\,b\,c\,e,\quad 
\el{a}{0.5}\,d\,e \to a\,b\,c\big\}
\end{align*}

**Combination phase**

It can be observed that $\mathcal D \subseteq \Sigma$, thus at this point, `change` is set to `false` and there is no need to iterate further.

## Final result

This is the direct system returned by the algorithm:

\begin{align*}
\Sigma_d = & \big\{
\el{a}{0.5}\,\el{b}{0.5}\,d \to a\,b\,c\,e,\quad 
\el{a}{0.5}\,d\,e \to a\,b\,c,\quad 
\el{d}{0.5}\,\el{e}{0.5} \to \el{a}{0.5}\,\el{b}{0.5}\,\el{c}{0.5},\quad 
\el{d}{0.5} \to \el{a}{0.5}\,\el{b}{0.5}\,\el{c}{0.5}\,\el{e}{0.5},\\
&\quad 
d\,e \to a\,b\,c,\quad 
d\,\el{e}{0.5} \to a\,b\,c\,e,\quad 
d \to a\,b\,c\,e\big\}
\end{align*}